backend:
  name: git-gateway
  repo: risingcampaigns/knowledgebase
  branch: master
site_url: https://docs.risingcampaigns.com
publish_mode: editorial_workflow
media_folder: "img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "articles" # Used in routes, e.g., /admin/collections/blog
    label: "Articles" # Used in the UI
    folder: "src/site/_content/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          # - { label: "parent", name: "parent", widget: "hidden", default: 'Articles' }
          - { label: "Parent Page", name: "parent", widget: "relation", collection: 'articles', default: "Articles", search_fields: ["title"], value_field: "eleventyNavigation: title", display_fields: ["title"], required: false }
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
          - { label: "Excerpt", name: "excerpt", widget: "text", default: 0, required: false }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Deck", name: "dek", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: faqs
    label: Frequently Asked Questions
    files:
      - file: src/site/_content/data/faqs.json
        name: faq
        label: Add FAQs
        fields: 
          - label: Heading
            name: hed
            widget: string
          - label: FAQ
            name: item
            widget: list
            fields: 
              - {label: Question, name: hed, widget: string}
              - {label: Anchor ID, name: id, widget: string}
              - {label: Answer, name: dek, widget: text, required: true}
  - name: glossary
    label: Glossary of Terms
    files:
      - file: src/site/_content/data/glossary.json
        name: faq
        label: Add Term
        fields: 
          - label: Page Titles
            name: hed
            widget: string
          - label: Terms
            name: item
            widget: list
            fields: 
              - {label: Term, name: hed, widget: string}
              - {label: Anchor ID, name: id, widget: string}
              - {label: Definition, name: dek, widget: text, required: true}
